### ISSUE TITLE
Is this an expected error? ( TypeError: object of type 'NoneType' has no len() )

### ISSUE THREAD

**Issue by asciifaceman** [liuhewei/gotools-sublime#23]
While waiting on an autocomplete:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 672, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Golang Tools Integration.sublime-package/gotools_suggestions.py", line 35, in on_query_completions
    if len(suggestionsJson) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by jcro21** [comment]
I'm getting the same issue
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 672, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/johnc/.config/sublime-text-3/Installed Packages/Golang Tools Integration.sublime-package/gotools_suggestions.py", line 35, in on_query_completions
    if len(suggestionsJson) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by asciifaceman** [comment]
This partially led to me and my team abandoning SublimeText, the entire ST ecosystem, especially around Go crumbled with 3 while vscode is solid as a rock

**Comment by jcro21** [comment]
Sad to hear, I've been using ST pretty much my whole career, I'd hate to have to leave but it's becoming more likely. :(

**Comment by asciifaceman** [comment]
same deal, ST for 10 years :(

also this isn't specific to gotools-sublime, they aren't at fault. the entire ST ecosystem fell apart

**Comment by pgomat** [comment]
I would have to leave it as well. it is irritating.
